name: stats
dependencies:
  - python==3.6.13
  - tensorflow
  - keras
  - tensorflow-gpu
  - tensorflow-estimator
  - bitsandbytes==0.35.4
  - transformers==4.26.0
  - triton
  - torch==1.12.1
  - torchvision==0.13.1
  - diffusers[torch]==0.11.1
  - decord==0.6.0
  - accelerate
  - tensorboard
  - modelcards
  - omegaconf
  - einops
  - imageio
  - ftfy
  - tensorrt
