name: stats
dependencies:
  - python==3.6.13
  - tensorflow
  - keras
  - tensorflow-gpu
  - tensorflow-estimator
  - bitsandbytes
  - transformers
  - triton
  - torch
  - torchvision
  - diffusers[torch]
  - decord
  - accelerate
  - tensorboard
  - modelcards
  - omegaconf
  - einops
  - imageio
  - ftfy
  - tensorrt
