name: stats
dependencies:
  - python==3.6.13
  - tensorflow
  - keras
  - tensorflow-gpu
  - tensorflow-estimator
  - bitsandbytes==0.35.4
  - transformers==4.26.0
  - triton
  - diffusers[torch]==0.11.1
  - accelerate
  - tensorboard
  - modelcards
  - omegaconf
  - einops
  - imageio
  - ftfy
  - pip
  - pip:
    - tensorrt
    - decord==0.6.0
    - torch==1.12.1
    - bitsandbytes==0.35.4
    - torchvision==0.13.1
